In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
df = pd.read_csv(r'D:\Data Analytics\Datasets\Extarcted\SMS Spam Collection Dataset\spam.csv',encoding = 'latin1')
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [12]:
df = df.iloc[:, :2]
df.columns = ["label", "message"]
df.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [13]:
import re # Regular expressions
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\SRIKAR
[nltk_data]     PILLALAMARRI\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [15]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [18]:
ps = PorterStemmer()
corpus = []
for i in range(0, len(df)):
    review = re.sub('[^a-zA-Z]', ' ', df['message'][i])
    review = review.lower()
    review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ''.join(review)
    corpus.append(review)

In [19]:
corpus

['g unl jurng pn  crz   vlble nl n bug n gre wrl l e buffe    cne here g re w   ',
 'k lr    jkng wf u n   ',
 'free enr n    wkl cp  wn f cup fnl k           ex f         receve enr quen  x re  c  ppl            ver   ',
 'u un   erl hr    u c lre hen    ',
 'nh  n  hnk he ge  uf  he lve run here hugh',
 'freeg he here rlng   been   week  nw n n wr bck    lke e fun u up fr  ll  b k  xxx  chg  en          rcv',
 'even  brher  n lke  pek wh e  he re e lke  pen ',
 ' per ur reque  elle elle  ru nnnungne nurungu ve   h been e  ur cllerune fr ll cller  pre     cp ur fren cllerune',
 'wnner     vlue newrk cuer u hve been elece  receve       prze rewr   cl cll              cl ce kl     vl    hur nl ',
 'h ur ble    nh r re  u r enle  upe  he le clur ble wh cer fr free  cll he ble upe c free n            ',
 '  gnn be he n n  n  wn  lk bu h uff nre ngh  k   ve cre enugh  ',
 'x chnce  wn ch  fr             pun x  ch   n en         c    p          nc ppl repl hl   nf',
 'urgen  u hve wn    wee

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 2500)

In [22]:
X = cv.fit_transform(corpus).toarray()

In [23]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [24]:
X.shape

(5572, 2500)

In [29]:
# For binary Bag of words
from sklearn.feature_extraction.text import CountVectorizer
cv1 = CountVectorizer(max_features = 2500, binary = True)
X1 = cv.fit_transform(corpus).toarray()

In [30]:
X1

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [31]:
cv.vocabulary_

{'unl': 2081,
 'pn': 1377,
 'crz': 347,
 'vlble': 2230,
 'nl': 1239,
 'bug': 127,
 'gre': 794,
 'wrl': 2429,
 'buffe': 126,
 'cne': 277,
 'here': 853,
 're': 1640,
 'lr': 1130,
 'jkng': 982,
 'wf': 2324,
 'free': 689,
 'enr': 507,
 'wkl': 2363,
 'cp': 303,
 'wn': 2388,
 'cup': 365,
 'fnl': 680,
 'ex': 576,
 'receve': 1651,
 'quen': 1602,
 'ppl': 1409,
 'ver': 2208,
 'un': 2040,
 'erl': 535,
 'hr': 911,
 'lre': 1131,
 'hen': 847,
 'nh': 1231,
 'hnk': 887,
 'he': 833,
 'ge': 744,
 'uf': 2002,
 'lve': 1152,
 'run': 1925,
 'hugh': 936,
 'freeg': 691,
 'rlng': 1844,
 'been': 14,
 'week': 2285,
 'nw': 1286,
 'wr': 2413,
 'bck': 4,
 'lke': 1099,
 'fun': 720,
 'up': 2105,
 'fr': 685,
 'll': 1103,
 'xxx': 2477,
 'chg': 206,
 'en': 482,
 'rcv': 1638,
 'even': 559,
 'brher': 105,
 'pek': 1324,
 'wh': 2327,
 'pen': 1327,
 'per': 1333,
 'ur': 2131,
 'reque': 1760,
 'elle': 467,
 'ru': 1904,
 'nnnungne': 1253,
 'nurungu': 1278,
 've': 2191,
 'cllerune': 259,
 'cller': 258,
 'pre': 1457,
 'fren': 696

### N-Gram

In [34]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 100, binary = True, ngram_range = (1,1))
X = cv.fit_transform(corpus).toarray()

In [35]:
cv.vocabulary_

{'pn': 71,
 'nl': 65,
 'gre': 30,
 'here': 36,
 're': 74,
 'lr': 55,
 'free': 25,
 'wn': 96,
 'ex': 21,
 'ver': 88,
 'un': 84,
 'hr': 42,
 'lre': 56,
 'hen': 34,
 'hnk': 39,
 'he': 33,
 'ge': 27,
 'lve': 57,
 'run': 81,
 'been': 3,
 'week': 90,
 'nw': 67,
 'wr': 97,
 'bck': 1,
 'lke': 53,
 'up': 85,
 'fr': 24,
 'll': 54,
 'en': 18,
 'wh': 92,
 'ur': 86,
 've': 87,
 'fren': 26,
 'hve': 45,
 'prze': 73,
 'cl': 8,
 'cll': 9,
 'ce': 6,
 'hur': 44,
 'ble': 4,
 'le': 50,
 'be': 2,
 'lk': 52,
 'bu': 5,
 'ngh': 63,
 'cre': 12,
 'ch': 7,
 'repl': 75,
 'hl': 37,
 'www': 99,
 'ne': 59,
 'rgh': 76,
 'ke': 48,
 'wll': 95,
 'ue': 83,
 'ege': 14,
 'eh': 15,
 'hw': 46,
 'we': 89,
 'new': 61,
 'gng': 29,
 'when': 93,
 'cn': 10,
 'ee': 13,
 'ju': 47,
 'knw': 49,
 'cr': 11,
 'wrk': 98,
 'pl': 69,
 'ng': 62,
 'ell': 17,
 'nhng': 64,
 'fer': 22,
 'plee': 70,
 'gn': 28,
 'her': 35,
 'rng': 77,
 'nee': 60,
 'rrw': 80,
 'hpe': 40,
 'well': 91,
 'ler': 51,
 'rnng': 78,
 'nce': 58,
 'hpp': 41,
 'rr': 79,
 'gve'

In [36]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 100, binary = True, ngram_range = (1,2))
X = cv.fit_transform(corpus).toarray()

In [37]:
cv.vocabulary_

{'pn': 71,
 'nl': 65,
 'gre': 31,
 'here': 37,
 're': 74,
 'lr': 55,
 'free': 26,
 'wn': 96,
 'ex': 21,
 'ver': 88,
 'un': 84,
 'hr': 42,
 'lre': 56,
 'hen': 35,
 'hnk': 40,
 'he': 34,
 'ge': 28,
 'lve': 57,
 'run': 81,
 'been': 3,
 'week': 90,
 'nw': 67,
 'wr': 97,
 'bck': 1,
 'lke': 53,
 'up': 85,
 'fr': 24,
 'll': 54,
 'en': 18,
 'wh': 92,
 'ur': 86,
 've': 87,
 'fren': 27,
 'hve': 45,
 'prze': 73,
 'cl': 8,
 'cll': 9,
 'ce': 6,
 'hur': 44,
 'ble': 4,
 'le': 50,
 'be': 2,
 'lk': 52,
 'bu': 5,
 'ngh': 63,
 'cre': 12,
 'ch': 7,
 'repl': 75,
 'hl': 38,
 'www': 99,
 'ne': 59,
 'rgh': 76,
 'ke': 48,
 'wll': 95,
 'fr he': 25,
 'ue': 83,
 'ege': 14,
 'eh': 15,
 'hw': 46,
 'we': 89,
 'new': 61,
 'gng': 30,
 'when': 93,
 'cn': 10,
 'ee': 13,
 'ju': 47,
 'knw': 49,
 'cr': 11,
 'wrk': 98,
 'pl': 69,
 'ng': 62,
 'ell': 17,
 'nhng': 64,
 'fer': 22,
 'plee': 70,
 'gn': 29,
 'her': 36,
 'rng': 77,
 'nee': 60,
 'rrw': 80,
 'hpe': 41,
 'well': 91,
 'ler': 51,
 'rnng': 78,
 'nce': 58,
 'rr': 79,
 'gv

In [38]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 100, binary = True, ngram_range = (2,2))
X = cv.fit_transform(corpus).toarray()

In [39]:
cv.vocabulary_

{'up fr': 72,
 'wh he': 87,
 'he re': 36,
 've been': 82,
 'ur fren': 76,
 'hve been': 44,
 'elece receve': 12,
 'ur ble': 73,
 'he le': 32,
 'be he': 0,
 'he wn': 39,
 'hve wn': 46,
 'he wr': 40,
 'fr he': 17,
 'hnk fr': 41,
 'ne he': 59,
 'll ur': 58,
 'he bu': 26,
 'we re': 86,
 'le knw': 54,
 'he cn': 27,
 'he ll': 33,
 'fr ur': 20,
 'wll be': 95,
 'when re': 92,
 'ee he': 11,
 'hw ur': 50,
 'he wh': 37,
 'hve gre': 45,
 'plee cll': 64,
 'cll nw': 7,
 'wh re': 88,
 'wn he': 97,
 're fr': 66,
 'bu he': 2,
 'he be': 25,
 'he new': 35,
 'knw wh': 53,
 'ur cll': 75,
 'rr ll': 71,
 'll cll': 56,
 'cll ler': 6,
 'pck up': 62,
 'he wll': 38,
 'ur re': 80,
 'urgen ur': 81,
 'where re': 93,
 'hw uch': 49,
 'he he': 30,
 'cuer ervce': 10,
 'we hve': 84,
 'ge he': 22,
 'ne ur': 60,
 'when ge': 90,
 'he ne': 34,
 'prze gurnee': 65,
 'gurnee cll': 24,
 'ur ccun': 74,
 'cll fr': 5,
 'fr lnlne': 19,
 'he fr': 29,
 're he': 67,
 'wng fr': 98,
 're ng': 69,
 're ll': 68,
 'new er': 61,
 'cn ke': 9,

### TF-IDF

In [40]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [41]:
corpus = []
for i in range(0, len(df)):
    review = re.sub('[^a-zA-Z]', ' ', df['message'][i])
    review = review.lower()
    review.split()
    review = [lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review = ''.join(review)
    corpus.append(review)

In [42]:
corpus

['g unl jurng pn  crz   vlble nl n bug n gre wrl l e buffe    cne here g re w   ',
 'k lr    jkng wf u n   ',
 'free enr n    wkl cp  wn f cup fnl k           ex f         receve enr quen  x re  c  ppl            ver   ',
 'u un   erl hr    u c lre hen    ',
 'nh  n  hnk he ge  uf  he lve run here hugh',
 'freeg he here rlng   been   week  nw n n wr bck    lke e fun u up fr  ll  b k  xxx  chg  en          rcv',
 'even  brher  n lke  pek wh e  he re e lke  pen ',
 ' per ur reque  elle elle  ru nnnungne nurungu ve   h been e  ur cllerune fr ll cller  pre     cp ur fren cllerune',
 'wnner     vlue newrk cuer u hve been elece  receve       prze rewr   cl cll              cl ce kl     vl    hur nl ',
 'h ur ble    nh r re  u r enle  upe  he le clur ble wh cer fr free  cll he ble upe c free n            ',
 '  gnn be he n n  n  wn  lk bu h uff nre ngh  k   ve cre enugh  ',
 'x chnce  wn ch  fr             pun x  ch   n en         c    p          nc ppl repl hl   nf',
 'urgen  u hve wn    wee

In [44]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features = 100)
X = tfidf.fit_transform(corpus).toarray()

In [46]:
np.set_printoptions(edgeitems = 30, linewidth = 100000,
                   formatter = dict(float = lambda x: "%.3g" % x))

In [47]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0.347, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.473, 0, 0, 0, 0.484, 0, 0, 0, 0, ..., 0, 0, 0, 0.324, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.543, 0, 0, 0, 0, 0, 0, 0, 0, 0.377, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.481, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.335, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.492, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [48]:
tfidf = TfidfVectorizer(max_features = 100, ngram_range = (2,2))
X = tfidf.fit_transform(corpus).toarray()

In [50]:
tfidf.vocabulary_

{'up fr': 72,
 'wh he': 87,
 'he re': 36,
 've been': 82,
 'ur fren': 76,
 'hve been': 45,
 'elece receve': 13,
 'ur ble': 73,
 'he le': 32,
 'cll he': 5,
 'be he': 0,
 'he wn': 39,
 'hve wn': 47,
 'he wr': 40,
 'fr he': 18,
 'hnk fr': 42,
 'ne he': 59,
 'cn ee': 8,
 'll ur': 58,
 'he bu': 27,
 'we re': 86,
 'le knw': 54,
 'he cn': 28,
 'he ll': 33,
 'fr ur': 21,
 'wll be': 95,
 'when re': 92,
 'ee he': 12,
 'he wh': 37,
 'hve gre': 46,
 'plee cll': 64,
 'cll nw': 7,
 'wh re': 88,
 'wn he': 97,
 're fr': 66,
 'bu he': 2,
 'he be': 26,
 'he new': 35,
 'knw wh': 53,
 'ur cll': 75,
 'rr ll': 71,
 'll cll': 56,
 'cll ler': 6,
 'pck up': 62,
 'he wll': 38,
 'ur re': 80,
 'urgen ur': 81,
 'where re': 93,
 'hw uch': 50,
 'he he': 31,
 'cuer ervce': 11,
 'we hve': 84,
 'ge he': 23,
 'ne ur': 60,
 'when ge': 90,
 'he ne': 34,
 'prze gurnee': 65,
 'gurnee cll': 25,
 'ur ccun': 74,
 'cll fr': 4,
 'fr lnlne': 20,
 'he fr': 30,
 're he': 67,
 'wng fr': 98,
 're ng': 69,
 're ll': 68,
 'new er': 61,